// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "supermart example",
    "version": "1.0.0"
  },
  "host": "supermart.org",
  "basePath": "/api",
  "paths": {
    "/items": {
      "get": {
        "tags": [
          "item"
        ],
        "operationId": "List",
        "parameters": [
          {
            "type": "string",
            "name": "items",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "item list",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/itemResponse"
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "item"
        ],
        "operationId": "Create",
        "parameters": [
          {
            "name": "item",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/item"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "item Created",
            "schema": {
              "$ref": "#/definitions/itemResponse"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/APIResponse"
            }
          }
        }
      }
    },
    "/items/{itemId}": {
      "get": {
        "tags": [
          "item"
        ],
        "operationId": "Get",
        "parameters": [
          {
            "type": "string",
            "name": "itemId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "item get",
            "schema": {
              "$ref": "#/definitions/itemResponse"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/APIResponse"
            }
          },
          "404": {
            "description": "item Not Found",
            "schema": {
              "$ref": "#/definitions/APIResponse"
            }
          }
        }
      },
      "put": {
        "tags": [
          "item"
        ],
        "operationId": "put",
        "parameters": [
          {
            "type": "string",
            "name": "itemId",
            "in": "path",
            "required": true
          },
          {
            "name": "item",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/item"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "item updated",
            "schema": {
              "$ref": "#/definitions/itemResponse"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "item"
        ],
        "operationId": "delete",
        "parameters": [
          {
            "type": "string",
            "name": "itemId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "item deleted"
          }
        }
      }
    }
  },
  "definitions": {
    "APIResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      }
    },
    "item": {
      "type": "object",
      "required": [
        "itemname"
      ],
      "properties": {
        "itemname": {
          "type": "string",
          "example": "teabag"
        },
        "price": {
          "type": "integer",
          "format": "int64",
          "example": 50
        },
        "quantity": {
          "type": "integer",
          "format": "int64",
          "example": 30
        }
      }
    },
    "itemResponse": {
      "type": "object",
      "properties": {
        "itemid": {
          "type": "string"
        },
        "itemname": {
          "type": "string",
          "example": "teabag"
        },
        "price": {
          "type": "integer",
          "format": "float64",
          "example": 50
        },
        "quantity": {
          "type": "integer",
          "example": 50
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "supermart example",
    "version": "1.0.0"
  },
  "host": "supermart.org",
  "basePath": "/api",
  "paths": {
    "/items": {
      "get": {
        "tags": [
          "item"
        ],
        "operationId": "List",
        "parameters": [
          {
            "type": "string",
            "name": "items",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "item list",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/itemResponse"
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "item"
        ],
        "operationId": "Create",
        "parameters": [
          {
            "name": "item",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/item"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "item Created",
            "schema": {
              "$ref": "#/definitions/itemResponse"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/APIResponse"
            }
          }
        }
      }
    },
    "/items/{itemId}": {
      "get": {
        "tags": [
          "item"
        ],
        "operationId": "Get",
        "parameters": [
          {
            "type": "string",
            "name": "itemId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "item get",
            "schema": {
              "$ref": "#/definitions/itemResponse"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/APIResponse"
            }
          },
          "404": {
            "description": "item Not Found",
            "schema": {
              "$ref": "#/definitions/APIResponse"
            }
          }
        }
      },
      "put": {
        "tags": [
          "item"
        ],
        "operationId": "put",
        "parameters": [
          {
            "type": "string",
            "name": "itemId",
            "in": "path",
            "required": true
          },
          {
            "name": "item",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/item"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "item updated",
            "schema": {
              "$ref": "#/definitions/itemResponse"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "item"
        ],
        "operationId": "delete",
        "parameters": [
          {
            "type": "string",
            "name": "itemId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "item deleted"
          }
        }
      }
    }
  },
  "definitions": {
    "APIResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      }
    },
    "item": {
      "type": "object",
      "required": [
        "itemname"
      ],
      "properties": {
        "itemname": {
          "type": "string",
          "example": "teabag"
        },
        "price": {
          "type": "integer",
          "format": "int64",
          "example": 50
        },
        "quantity": {
          "type": "integer",
          "format": "int64",
          "example": 30
        }
      }
    },
    "itemResponse": {
      "type": "object",
      "properties": {
        "itemid": {
          "type": "string"
        },
        "itemname": {
          "type": "string",
          "example": "teabag"
        },
        "price": {
          "type": "integer",
          "format": "float64",
          "example": 50
        },
        "quantity": {
          "type": "integer",
          "example": 50
        }
      }
    }
  }
}`))
}
