// Code generated by go-swagger; DO NOT EDIT.

package item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ASinha24/supermartswaggerAPI/models"
)

// GetReader is a Reader for the Get structure.
type GetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetOK creates a GetOK with default headers values
func NewGetOK() *GetOK {
	return &GetOK{}
}

/*GetOK handles this case with default header values.

item get
*/
type GetOK struct {
	Payload *models.ItemResponse
}

func (o *GetOK) Error() string {
	return fmt.Sprintf("[GET /items/{itemId}][%d] getOK  %+v", 200, o.Payload)
}

func (o *GetOK) GetPayload() *models.ItemResponse {
	return o.Payload
}

func (o *GetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ItemResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBadRequest creates a GetBadRequest with default headers values
func NewGetBadRequest() *GetBadRequest {
	return &GetBadRequest{}
}

/*GetBadRequest handles this case with default header values.

Bad Request
*/
type GetBadRequest struct {
	Payload *models.APIResponse
}

func (o *GetBadRequest) Error() string {
	return fmt.Sprintf("[GET /items/{itemId}][%d] getBadRequest  %+v", 400, o.Payload)
}

func (o *GetBadRequest) GetPayload() *models.APIResponse {
	return o.Payload
}

func (o *GetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNotFound creates a GetNotFound with default headers values
func NewGetNotFound() *GetNotFound {
	return &GetNotFound{}
}

/*GetNotFound handles this case with default header values.

item Not Found
*/
type GetNotFound struct {
	Payload *models.APIResponse
}

func (o *GetNotFound) Error() string {
	return fmt.Sprintf("[GET /items/{itemId}][%d] getNotFound  %+v", 404, o.Payload)
}

func (o *GetNotFound) GetPayload() *models.APIResponse {
	return o.Payload
}

func (o *GetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
